services:
  web:
    build: .
    ports: ["3000:3000"]
    env_file: [.env.dev]
    depends_on: [db]
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
